Traceback (most recent call last):
  File "/home/robert/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/robert/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
T0 = 350*T0overT(3.5)
Markdown('$T_0 =$ {:.4g} K'.format(T0))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [8][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m T0 [38;5;241m=[39m [38;5;241m350[39m[38;5;241m*[39mT0overT([38;5;241m3.5[39m)
[0;32m----> 2[0m [43mMarkdown[49m([38;5;124m'[39m[38;5;124m$T_0 =$ [39m[38;5;132;01m{:.4g}[39;00m[38;5;124m K[39m[38;5;124m'[39m[38;5;241m.[39mformat(T0))

[0;31mNameError[0m: name 'Markdown' is not defined
NameError: name 'Markdown' is not defined

