Traceback (most recent call last):
  File "/home/robert/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/robert/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/robert/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import statsmodels.api as sm
rho = sm.tsa.acf(uPrime,nlags=50,fft=False)
rho
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [29][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mas[39;00m [38;5;21;01msm[39;00m
[1;32m      2[0m rho [38;5;241m=[39m sm[38;5;241m.[39mtsa[38;5;241m.[39macf(uPrime,nlags[38;5;241m=[39m[38;5;241m50[39m,fft[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m      3[0m rho

File [0;32m~/anaconda3/lib/python3.8/site-packages/statsmodels/api.py:27[0m, in [0;36m<module>[0;34m[0m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mdiscrete[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdiscrete_model[39;00m [38;5;28;01mimport[39;00m (Poisson, Logit, Probit,
[1;32m     21[0m                                       MNLogit, NegativeBinomial,
[1;32m     22[0m                                       GeneralizedPoisson,
[1;32m     23[0m                                       NegativeBinomialP)
[1;32m     24[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mdiscrete[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcount_model[39;00m [38;5;28;01mimport[39;00m (ZeroInflatedPoisson,
[1;32m     25[0m                                    ZeroInflatedGeneralizedPoisson,
[1;32m     26[0m                                    ZeroInflatedNegativeBinomialP)
[0;32m---> 27[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtsa[39;00m [38;5;28;01mimport[39;00m api [38;5;28;01mas[39;00m tsa
[1;32m     28[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mduration[39;00m[38;5;21;01m.[39;00m[38;5;21;01msurvfunc[39;00m [38;5;28;01mimport[39;00m SurvfuncRight
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mduration[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhazard_regression[39;00m [38;5;28;01mimport[39;00m PHReg

File [0;32m~/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/api.py:31[0m, in [0;36m<module>[0;34m[0m
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mvector_ar[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvecm[39;00m [38;5;28;01mimport[39;00m VECM
[1;32m     30[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mvector_ar[39;00m[38;5;21;01m.[39;00m[38;5;21;01msvar_model[39;00m [38;5;28;01mimport[39;00m SVAR
[0;32m---> 31[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mfilters[39;00m [38;5;28;01mimport[39;00m api [38;5;28;01mas[39;00m filters
[1;32m     32[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m tsatools
[1;32m     33[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtsatools[39;00m [38;5;28;01mimport[39;00m (add_trend, detrend, lagmat, lagmat2ds, add_lag)

File [0;32m~/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/filters/api.py:6[0m, in [0;36m<module>[0;34m[0m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mhp_filter[39;00m [38;5;28;01mimport[39;00m hpfilter
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcf_filter[39;00m [38;5;28;01mimport[39;00m cffilter
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mfiltertools[39;00m [38;5;28;01mimport[39;00m miso_lfilter, convolution_filter, recursive_filter

File [0;32m~/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/filters/filtertools.py:18[0m, in [0;36m<module>[0;34m[0m
[1;32m     16[0m [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfftpack[39;00m [38;5;28;01mas[39;00m [38;5;21;01mfft[39;00m
[1;32m     17[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m signal
[0;32m---> 18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01msignal[39;00m[38;5;21;01m.[39;00m[38;5;21;01msignaltools[39;00m [38;5;28;01mimport[39;00m _centered [38;5;28;01mas[39;00m trim_centered
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtools[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvalidation[39;00m [38;5;28;01mimport[39;00m array_like, PandasWrapper
[1;32m     22[0m [38;5;28;01mdef[39;00m [38;5;21m_pad_nans[39m(x, head[38;5;241m=[39m[38;5;28;01mNone[39;00m, tail[38;5;241m=[39m[38;5;28;01mNone[39;00m):

[0;31mImportError[0m: cannot import name '_centered' from 'scipy.signal.signaltools' (/home/robert/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py)
ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/home/robert/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py)

